### ISSUE TITLE
Looking for someone who has multiple windshares in different windturbines?

### ISSUE THREAD

**Issue by jobvk** [jobvk/Home-Assistant-Windcentrale#10]
## I'm Looking for someone who has multiple windshares in different windturbines? 

I am trying to change the settings of the setup. Now you have to fill in how many wind parts you own by yourself. 

My goal is that you enter your email and password and that custom component knows how many windshares you have of specific windturbine. With the help of reverse engineering I have already managed to retrieve this data for myself. But I only own windshares in a single windturbine. So to make sure this works well, I'm looking for someone with windshares in several windturbines.

If you want to help me with this problem solving please comment on this issue or add me on [discord](https://discord.com/invite/T3tK4Jsquc)

**Comment by vdheidenet** [comment]
Hi Job,

I've got 12 windshares in 3 different turbines.
How can I help?

Kind Regards,
Marco van der Heide

**Comment by jobvk** [comment]
Hi @vdheidenet,

We need to get a json file from the windcentrale website. For this you need your own login details and some knowledge of [Postman](https://www.postman.com/) or Python. I don't know how much knowledge you have about this.

The point is that you need the login details for this and the json file that is returned contains name and address details. It's not helpful if this data is public on github.

So I suggest you add me on [discord](https://discord.com/invite/T3tK4Jsquc). Then I'll explain it to you via chat or via a call. What needs to be done.

Kind Regards,

Job van Koeveringe

**Comment by jobvk** [comment]
Hi @vdheidenet,

I think I got it working. Could you please test the version [0.1.4](https://github.com/jobvk/Home-Assistant-Windcentrale/releases/tag/0.1.4)?

Let me know if it works fine of something did go wrong,

Kind Regards,

Job van Koeveringe

**Comment by mschut** [comment]
I just upgraded from 0.1.3 to 0.1.4. Unfortunately, I only see one windmill while I own shares of two mills. Because I had some questions I contacted Windcentrale yesterday and realised there are two platformns (the old and the new one). The "old" one is not maintained anymore, so I am not able to see my new shares of the seceond mill there, the Windcentrale told me. I can see it however on the "new" platform (https://mijn.windcentrale.nl/). For the integration in HA I have to use my credentials for the former platform (https://mijnmolen.windcentrale.nl/), and indeed I can only see one windmill in HA now. 

I would guess that this integration is using the information of the former platform, which is not maintained anymore. Could the integration be updated to the new palform, or is there another option with to add a second mill manually with 0.1.4, as I did with 0.1.3.

**Comment by jobvk** [comment]
Hi @mschut,

I will look into the "new" platform. Because I haven't seen or heard anything about any new platform and seems more like something for windshares bought through Coolblue. Did you buy them through Coolbue by any chance? For now you can just use version 0.1.3. Because there you can adjust the windshares by hand.

**Comment by mschut** [comment]
I indeed did revert to 0.1.3 already. If you want to buy new shares you can only do this now on (what they call) the new platform, where you see Coolblue. All the information is still at "the old paltform", so still correct, unless something changes in your amount of windshares. This won't be corrected there anymore as I understand.

**Comment by mschut** [comment]
Hi Job, I noticed an update on the extension. Due to multiple shares I am still on version 0.1.3. Does the new version point to the "new" platform already?

**Comment by jobvk** [comment]
They are still working on the new platform, recently they added production & live API's to the new platform.
If the new platform is released then I will look in to the new platform with the new login function with the new API's.
