### ISSUE TITLE
Sensor is made availabe for Energy Management tab

### ISSUE THREAD

**Issue by Simanias** [jobvk/Home-Assistant-Windcentrale#6]
### Checklist

- [X] I'm not requesting to add this integration to Home Assistant Core.
- [X] I checked if there is not a duplicate feature request with the same question.
- [x] I have read the paragraph ToDo on the [README.md](https://github.com/jobvk/Home-Assistant-Windcentrale/blob/master/README.md#todo) Page. And I checked if my feature request is not already there.
- [X] This feature request is a related to the Windcentrale integration.
- [X] This feature request only contains 1 request (if you have multiple feature requests, open one request for each request).
- [x] I have filled out the feature request template to the best of my ability.

### The Feature Request

Via these parameters which should be in the customize.yaml of your Home Assistant instance, the sensor is made available for the Energy Management tab. 
Replace the sensor.'name' with your name for the winddelen energy sensor.
After this, restart your Home Assistant instance and add the winddelen sensor via Configuration > Energy > Add Return > Select your windelen sensor.

### Example Code snippet

```

sensor.'name':
  state_class: total_increasing
```

**Comment by jobvk** [comment]
I'm already testing this for a week of two.
Every day sensor has now attribute "last_reset" and "state_class".

![image](https://user-images.githubusercontent.com/32730202/140642859-8b595a61-2650-4ac8-9551-46863fe6f3ec.png)

The state_class is "total" and not "total_increasing" because of energy use of the windturbine. If the windturbine is not spinning the windturbine can use more power than it produces. Found this on their site:

![image](https://user-images.githubusercontent.com/32730202/140643066-aa6679d9-82de-4316-8627-3339c1475b67.png)

But there is also the problem of putting the data inside home assistant. The API of the production history updates every couple of minutes. But as seen on the image below the API update after 06:59 an changes the data of the windcentrale graph. But I can't update home assistant state because the hour is already past.

Home Assistant
![image](https://user-images.githubusercontent.com/32730202/140643312-0836568f-5acf-4369-a135-9a6b7a6629ac.png)
Windcentrale app
![image](https://user-images.githubusercontent.com/32730202/140643292-7ea72af5-0846-4c2a-8ffb-5ce837486b6e.png)

@Simanias  If you want to help me with this problem solving please add me on [discord](https://discord.com/invite/T3tK4Jsquc)

Next week i'm going to check if it is possible to override data after the hour has been passed.

**Comment by creativethings** [comment]
Hey,
I am trying to get this working. However I am not getting very far :( 
I added 
```
sensor.het_rode_hert:
  state_class: total_increasing
```
I cannot add the sensor to the energy panel however, it is not even listed in Configuration > Energy > Add Return
I'm using v0.1.1 of the integration.

Any suggestions?
many thanks!

**Comment by jobvk** [comment]
@creativethings @Simanias I created a beta(pre-release) [0.1.2-beta](https://github.com/jobvk/Home-Assistant-Windcentrale/releases/tag/0.1.2-Beta)

With this pre-release you can add sensor to the Energy Management tab but the graph is still perfect. Because I haven't found a solution to update home assistant after the hour/day past.

**Comment by Simanias** [comment]
@jobvk with the beta release the sensor can indeed be selected in the energy management tab, great work.
Hopefully you're able to sort things out with regard to the wrong timing.

**Comment by creativethings** [comment]
Hi @jobvk,
I can confirm it works with the 0.1.2. release for "Het Rode Hert" as well, great! I do not have multiple mill shares I am sorry, so I cannot test that scenario.

I am wondering where best to add the sensor. As far as I can see there is no way to create additional energy sources (or did i miss something?), but I can add it as fake solar result, in which case it shows up as part of my solar data.

In reality the power produced ofcause never enters my house and gets taken into account only at billing time. 
I was wondering therefor if it would make sense to add the winddeler result to the Net consumption, but then as a negative value. Benefit would also be that it automatically shows up in the energy consumption chart as a separate value. For that to be correct I would have however have to be able to set negative values. How would I do that?

I added this to connfiuration.yaml and although the value is calculated correctly, I cannot add it to the energy panel as a value :(
```
  - platform: template
    sensors:
        het_rode_hert_virtual_consumption:
        friendly_name: 'Het Rode Hert productie virtueel'
        unit_of_measurement: "kWh"  
        device_class: energy
        value_template: >-
            {{ ( states('sensor.het_rode_hert') | float / -1000 )  | round(2) }} ```

**Comment by jobvk** [comment]
Hi @creativethings,
Good to hear it's working.

Your virtual sensor is W not kWh so that can be one reason it doesn't work.
If you want to W to kWh you can use [Riemann sum](https://www.home-assistant.io/integrations/integration/)

If you want your virtual sensor in to Energy Management tab you van try this:

```
homeassistant:
  customize_glob:
    sensor.het_rode_hert_virtual_consumption:
      last_reset: "1970-01-01T00:00:00+00:00"
      device_class: energy
      state_class: measurement
```

## You have to change the value maybe depending on your need.

https://developers.home-assistant.io/docs/core/entity/sensor/

### device_class
`device_class: power` Supported units: W & kW. Power, statistics will be stored in W.
`device_class: energy`  Supported units: Wh, kWh, MWh. statistics will be stored in kWh.

### state_class
`state_class: measurement ` is best if the values changes every time in to something. (No last_reset is necessary)
`state_class: total`  is best if the value is only going up and down is a line.  You have to use last_reset.
`state_class: total_increasing`  is best if the value is only going up. You have to use last_reset.

**Comment by vressel** [comment]
Hi,

I'm a newbie at HomeAssistant, and trying to make the output of my 2 shares of the "De Blauwe Reiger" visible in the EnergyManagementTab. 

I now made this template:

    - name: Wind Totaal kWh
      unit_of_measurement: "kWh"
      state: "{{ '%0.2f' | format(states('sensor.de_blauwe_reiger_total_production') | float(default=0) * 1000)  }}"
      state_class: total_increasing
      device_class: energy

Because the value is only going up I can use total_increasing, so there's no bother with last_reset. 

It would be nicer if the output had better resolution and should be in Wh, and because my shell-scripting is much better than my python-programming:

VALUE=$(curl -s https://zep-api.windcentrale.nl/production/131 | grep LIFETIME | awk -F\" '{print $(NF-1)}' | awk -FE '{print $1}' )
VALUE_Wh=$(echo $VALUE \* 10000000000 / 5534 \* 2 | bc)

This should give you the value of shares for the lifetime of the windmill in Wh.

Is it possible to add this to the Windcentrale-integration?

**Comment by jobvk** [comment]
Hi @vressel,

Why do you want to use the `sensor.de_blauwe_reiger_total_production` sensor? If you use version [0.1.2](https://github.com/jobvk/Home-Assistant-Windcentrale/releases/tag/0.1.2) you can add `sensor.de_blauwe_reiger_day_production` to the Energy Managemen Tab and it works perfectly fine.

The reason why it's "total" and not "total_increasing" van be found here:

> The state_class is "total" and not "total_increasing" because of energy use of the windturbine. If the windturbine is not spinning the windturbine can use more power than it produces. Found this on their site:
> 
> ![image](https://user-images.githubusercontent.com/32730202/140643066-aa6679d9-82de-4316-8627-3339c1475b67.png)

The `year_production` & `total_production` are in MWh, it's the same electric unit as used in their app. It's easy to read. 
If you change it to Wh the output would be a really long value with a lot of decimals, and that's not really easy to read.

So I Don't see a point why I should change the value to Wh.

**Comment by vressel** [comment]
Hi @jobvk 

Thnx for your reaction.

I think I'm using 0.1.2 (according to custom_compnents/windcentrale/manifest.json), but selecting sensor.de_blauwe_reiger_day_production gives a message"unexpected state class".

I can modify customize.yaml:
sensor.de_blauwe_reiger_day_production:
  state_class: total

but then it messes up my view:

![image](https://user-images.githubusercontent.com/95576547/144754838-41fd8d5e-9d57-4ea1-bf0d-4133ed5a96ce.png)

![image](https://user-images.githubusercontent.com/95576547/144754878-7b77ce8b-b60d-4c29-9146-64c923b16fa0.png)

**Comment by jobvk** [comment]
@vressel please create a new issue. 
Please include log or picture of the error. And witch step it took to create this error.
